### ISSUE TITLE
Expiration of the lock

### ISSUE THREAD

**Issue by OrKoN** [blockai/advisory-lock#3]
Hi,

is it possible to set an expiration for the lock? What will happen if the process dies without releasing the lock?

Best regards,
Alex

**Comment by olalonde** [comment]
From https://www.postgresql.org/docs/9.1/static/explicit-locking.html

> Once acquired at session level, an advisory lock is held until explicitly released or the session ends. 

So the lock would be immediately released if the process crashes/dies (advisory-lock uses session level advisory locks). Does that answer your question?

**Comment by OrKoN** [comment]
@olalonde and if the process for some reason keeps running but due to some errors/bugs/unexpected conditions does not release the lock?

**Comment by olalonde** [comment]
I don't think that's possible with postgresql advisory locks unfortunately.

**Comment by OrKoN** [comment]
Thanks @olalonde
